#!/bin/sh

echo "Switching to branch master"
git checkout master

echo "Building app"
npm run build

echo "Deploying files to server"
rsync -avP build/ rajal@rajalkumar.com:/var/www/rajalkumar.com/
echo "Deployment complete"
